name: result_o3
description: A Result type inspired by Rust for the Dart programming language
version: 1.0.1
repository: https://github.com/gekkotadev/sealed_results

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
